from pages.models import Library, FloorSection, hoursOfOp, recordData

grainger = Library(libName='Grainger', libraryDept='Engineering', numFloors=4, libAddress='1301 W Springfield Ave, Urbana, IL 61801', reservationLink='https://uiuc.libcal.com/spaces?lid=3606')
chemLib = Library(libName='Chemistry Library', libraryDept='Chemistry', numFloors=1, libAddress='505 S Mathews Ave, Urbana, IL 61801', reservationLink='https://uiuc.libcal.com/spaces?lid=5903')
mainLib = Library(libName='Main Library', libraryDept='LAS', numFloors=2, libAddress='1408 W Gregory Dr, Urbana, IL 61801', reservationLink='https://uiuc.libcal.com/spaces?lid=3608')
ugl = Library(libName='UGL', libraryDept='LAS', numFloors=2, libAddress='1402 W Gregory Dr, Urbana, IL 61801', reservationLink='https://uiuc.libcal.com/spaces?lid=3152')
acesLib = Library(libName='ACES Library', libraryDept='ACES', numFloors=3, libAddress='1101 S Goodwin Ave, Urbana, IL 61801')

grainger.save()
chemLib.save()
mainLib.save()
ugl.save()
acesLib.save()

Library.objects.all()

grainger4W = FloorSection(libName='Grainger', floorNum=5, section='West', numSeats=106, studyEnv='Group Study')
grainger4C = FloorSection(libName='Grainger', floorNum=5, section='Central', numSeats=106, studyEnv='Group Study')
grainger4EWS = FloorSection(libName='Grainger', floorNum=5, section='EWS', numSeats=106, studyEnv='EWS Station')
grainger4E = FloorSection(libName='Grainger', floorNum=5, section='East', numSeats=106, studyEnv='Group Study')
grainger3 = FloorSection(libName='Grainger', floorNum=4, section='ALL', numSeats=75, studyEnv='Quiet Closed Study')
grainger2 = FloorSection(libName='Grainger', floorNum=3, section='ALL', numSeats=550, studyEnv='Quiet Closed Study')
grainger1W = FloorSection(libName='Grainger', floorNum=2, section='West', numSeats=86, studyEnv='Group Study')
grainger1EWS = FloorSection(libName='Grainger', floorNum=2, section='EWS', numSeats=88, studyEnv='EWS Station')
grainger0 = FloorSection(libName= 'Grainger', floorNum = 1, section = 'ALL', numSeats = 175, studyEnv='Group Study')
chemLib1 = FloorSection(libName='Chemistry Library', floorNum=1, section='Noyes', numSeats=77, studyEnv='Quiet Open Study')
mainLib1 = FloorSection(libName='Main Library', floorNum=1, section='ALL', numSeats=264, studyEnv='Quiet Open Study')
mainLib2 = FloorSection(libName='Main Library', floorNum=2, section='ALL', numSeats=434, studyEnv='Quiet Open Study')
UGL2 = FloorSection(libName='UGL', floorNum=2, section='ALL', numSeats=384, studyEnv='Group Study')
UGL1 = FloorSection(libName='UGL', floorNum=1, section='ALL', numSeats=720, studyEnv='Quiet Open Study')
ACESfloor2 = FloorSection(libName = 'ACES Library', floorNum = 2, section = 'ALL', numSeats = 120, studyEnv = 'Group Study')
ACESfloor3 = FloorSection(libName = 'ACES Library', floorNum = 3, section = 'ALL', numSeats = 120, studyEnv = 'Group Study')
ACESfloor4 = FloorSection(libName = 'ACES Library', floorNum = 4, section = 'ALL', numSeats = 120, studyEnv = 'Quiet Open Study')
ACESfloor5 = FloorSection(libName = 'ACES Library', floorNum = 5, section = 'ALL', numSeats = 120, studyEnv = 'Quiet Open Study')

grainger4W.save()
grainger4C.save()
grainger4EWS.save()
grainger4E.save()
grainger3.save()
grainger2.save()
grainger1W.save()
grainger1EWS.save()
grainger0.save()
chemLib1.save()
mainLib1.save()
mainLib2.save()
UGL1.save()
UGL2.save()
ACESfloor2.save()
ACESfloor3.save()
ACESfloor4.save()
ACESfloor5.save()

FloorSection.objects.all()

ACES7 = hoursOfOp(libName = 'ACES Library', dayOfWeek = 7, openTime = 1000, closeTime = 2400)
ACES1 = hoursOfOp(libName = 'ACES Library', dayOfWeek = 1, openTime = 830, closeTime = 2400)
ACES2 = hoursOfOp(libName = 'ACES Library', dayOfWeek = 2, openTime = 830, closeTime = 2400)
ACES3 = hoursOfOp(libName = 'ACES Library', dayOfWeek = 3, openTime = 830, closeTime = 2400)
ACES4 = hoursOfOp(libName = 'ACES Library', dayOfWeek = 4, openTime = 830, closeTime = 2400)
ACES5 = hoursOfOp(libName = 'ACES Library', dayOfWeek = 5, openTime = 830, closeTime = 2100)
ACES6 = hoursOfOp(libName = 'ACES Library', dayOfWeek = 6, openTime = 1000, closeTime = 2100)
UGL7 = hoursOfOp(libName = 'UGL', dayOfWeek = 7, openTime = 1000, closeTime = 2400)
UGL1 = hoursOfOp(libName = 'UGL', dayOfWeek = 1, openTime = 730, closeTime = 2400)
UGL2 = hoursOfOp(libName = 'UGL', dayOfWeek = 2, openTime = 730, closeTime = 2400)
UGL3 = hoursOfOp(libName = 'UGL', dayOfWeek = 3, openTime = 730, closeTime = 2400)
UGL4 = hoursOfOp(libName = 'UGL', dayOfWeek = 4, openTime = 730, closeTime = 2400)
UGL5 = hoursOfOp(libName = 'UGL', dayOfWeek = 5, openTime = 730, closeTime = 2100)
UGL6 = hoursOfOp(libName = 'UGL', dayOfWeek = 6, openTime = 1000, closeTime = 2100)
Main7 = hoursOfOp(libName = 'Main Library', dayOfWeek = 7, openTime = 1300, closeTime = 2200)
Main1 = hoursOfOp(libName = 'Main Library', dayOfWeek = 1, openTime = 830, closeTime = 2200)
Main2 = hoursOfOp(libName = 'Main Library', dayOfWeek = 2, openTime = 830, closeTime = 2200)
Main3 = hoursOfOp(libName = 'Main Library', dayOfWeek = 3, openTime = 830, closeTime = 2200)
Main4 = hoursOfOp(libName = 'Main Library', dayOfWeek = 4, openTime = 830, closeTime = 2200)
Main5 = hoursOfOp(libName = 'Main Library', dayOfWeek = 5, openTime = 830, closeTime = 1800)
Main6 = hoursOfOp(libName = 'Main Library', dayOfWeek = 6, openTime = 1300, closeTime = 1700)
Chem7 = hoursOfOp(libName = 'Chemistry Library', dayOfWeek = 7, openTime = 1300, closeTime = 2200)
Chem1 = hoursOfOp(libName = 'Chemistry Library', dayOfWeek = 1, openTime = 900, closeTime = 2200)
Chem2 = hoursOfOp(libName = 'Chemistry Library', dayOfWeek = 2, openTime = 900, closeTime = 2200)
Chem3 = hoursOfOp(libName = 'Chemistry Library', dayOfWeek = 3, openTime = 900, closeTime = 2200)
Chem4 = hoursOfOp(libName = 'Chemistry Library', dayOfWeek = 4, openTime = 900, closeTime = 2200)
Chem5 = hoursOfOp(libName = 'Chemistry Library', dayOfWeek = 5, openTime = 900, closeTime = 1700)
Chem6 = hoursOfOp(libName = 'Chemistry Library', dayOfWeek = 6, openTime = 1300, closeTime = 1700)
Grainger7= hoursOfOp(libName = 'Grainger', dayOfWeek = 7, openTime = 1000, closeTime = 2400)
Grainger1= hoursOfOp(libName = 'Grainger', dayOfWeek = 1, openTime = 0, closeTime = 2400)
Grainger2= hoursOfOp(libName = 'Grainger', dayOfWeek = 2, openTime = 0, closeTime = 2400)
Grainger3= hoursOfOp(libName = 'Grainger', dayOfWeek = 3, openTime = 0, closeTime = 2400)
Grainger4= hoursOfOp(libName = 'Grainger', dayOfWeek = 4, openTime = 0, closeTime = 2400)
Grainger5= hoursOfOp(libName = 'Grainger', dayOfWeek = 5, openTime = 0, closeTime = 2400)
Grainger6= hoursOfOp(libName = 'Grainger', dayOfWeek = 6, openTime = 1000, closeTime = 2400)

'''ACES1.save()
ACES2.save()
ACES3.save()
ACES4.save()
ACES5.save()
ACES6.save()
ACES7.save()
UGL1.save()
UGL2.save()
UGL3.save()
UGL4.save()
UGL5.save()
UGL6.save()
UGL7.save()
Main1.save()
Main2.save()
Main3.save()
Main4.save()
Main5.save()
Main6.save()
Main7.save()
Grainger1.save()
Grainger2.save()
Grainger3.save()
Grainger4.save()
Grainger5.save()
Grainger6.save()
Grainger7.save()
Chem1.save()
Chem2.save()
Chem3.save()
Chem4.save()
Chem5.save()
Chem6.save()
Chem7.save()'''

hoursOfOp.objects.all()
