from pages.models import Library, FloorSection, hoursOfOp

grainger = Library(libName='Grainger', libraryDept='Engineering', numFloors=4, libAddress='1301 W Springfield Ave, Urbana, IL 61801', reservationLink='https://uiuc.libcal.com/spaces?lid=3606')
chemLib = Library(libName='Chemistry Library', libraryDept='Chemistry', numFloors=1, libAddress='505 S Mathews Ave, Urbana, IL 61801', reservationLink='https://uiuc.libcal.com/spaces?lid=5903')
mainLib = Library(libName='Main Library', libraryDept='LAS', numFloors=2, libAddress='1408 W Gregory Dr, Urbana, IL 61801', reservationLink='https://uiuc.libcal.com/spaces?lid=3608')
ugl = Library(libName='UGL', libraryDept='LAS', numFloors=2, libAddress='1402 W Gregory Dr, Urbana, IL 61801', reservationLink='https://uiuc.libcal.com/spaces?lid=3152')
acesLib = Library(libName='ACES Library', libraryDept='ACES', numFloors=3, libAddress='1101 S Goodwin Ave, Urbana, IL 61801')

grainger.save()
chemLib.save()
mainLib.save()
ugl.save()
acesLib.save()

Library.objects.all()

grainger4W = FloorSection(libName='Grainger', floorNum=4, section='West', numSeats=107, studyEnv='collaborative')
grainger4C = FloorSection(libName='Grainger', floorNum=4, section='Central', numSeats=102, studyEnv='collaborative')
grainger4EWS = FloorSection(libName='Grainger', floorNum=4, section='EWS', numSeats=100, studyEnv='EWS')
grainger4E = FloorSection(libName='Grainger', floorNum=4, section='East', numSeats=32, studyEnv='collaborative')
grainger3 = FloorSection(libName='Grainger', floorNum=3, section='All', numSeats=85, studyEnv='quiet')
grainger2 = FloorSection(libName='Grainger', floorNum=2, section='All', numSeats=557, studyEnv='quiet')
grainger1W = FloorSection(libName='Grainger', floorNum=1, section='West', numSeats=0, studyEnv='collaborative')
grainger1EWS = FloorSection(libName='Grainger', floorNum=1, section='EWS', numSeats=0, studyEnv='collaborative')
chemLib1 = FloorSection(libName='Chemistry Library', floorNum=1, section='Noyes', numSeats=77, studyEnv='quiet')
mainLib1 = FloorSection(libName='Main Library', floorNum=1, section='All', numSeats=264, studyEnv='quiet')
mainLib2 = FloorSection(libName='Main Library', floorNum=2, section='All', numSeats=434, studyEnv='quiet')
UGL1 = FloorSection(libName='UGL', floorNum=1, section='All', numSeats=384, studyEnv='collaborative')
UGL2 = FloorSection(libName='UGL', floorNum=2, section='All', numSeats=720, studyEnv='quiet')

grainger4W.save()
grainger4C.save()
grainger4EWS.save()
grainger4E.save()
grainger3.save()
grainger2.save()
grainger1W.save()
grainger1EWS.save()
chemLib1.save()
mainLib1.save()
mainLib2.save()
UGL1.save()
UGL2.save()

FloorSection.objects.all()

ACES0 = hoursOfOp(libName = 'ACES', dayOfWeek = 0, openTime = 0, closeTime = 0)
ACES1 = hoursOfOp(libName = 'ACES', dayOfWeek = 1, openTime = 830, closeTime = 1700)
ACES2 = hoursOfOp(libName = 'ACES', dayOfWeek = 2, openTime = 830, closeTime = 1700)
ACES3 = hoursOfOp(libName = 'ACES', dayOfWeek = 3, openTime = 830, closeTime = 1430)
ACES4 = hoursOfOp(libName = 'ACES', dayOfWeek = 4, openTime = 830, closeTime = 1430)
ACES5 = hoursOfOp(libName = 'ACES', dayOfWeek = 5, openTime = 830, closeTime = 1900)
ACES6 = hoursOfOp(libName = 'ACES', dayOfWeek = 6, openTime = 0, closeTime = 0)
UGL0 = hoursOfOp(libName = 'UGL', dayOfWeek = 0, openTime = 0, closeTime = 0)
UGL1 = hoursOfOp(libName = 'UGL', dayOfWeek = 1, openTime = 830, closeTime = 1700)
UGL2 = hoursOfOp(libName = 'UGL', dayOfWeek = 2, openTime = 830, closeTime = 1700)
UGL3 = hoursOfOp(libName = 'UGL', dayOfWeek = 3, openTime = 730, closeTime = 1430)
UGL4 = hoursOfOp(libName = 'UGL', dayOfWeek = 4, openTime = 730, closeTime = 1430)
UGL5 = hoursOfOp(libName = 'UGL', dayOfWeek = 5, openTime = 730, closeTime = 1900)
UGL6 = hoursOfOp(libName = 'UGL', dayOfWeek = 6, openTime = 0, closeTime = 0)
Main0 = hoursOfOp(libName = 'Main Library', dayOfWeek = 0, openTime = 0, closeTime = 0)
Main1 = hoursOfOp(libName = 'Main Library', dayOfWeek = 1, openTime = 830, closeTime = 1700)
Main2 = hoursOfOp(libName = 'Main Library', dayOfWeek = 2, openTime = 830, closeTime = 1700)
Main3 = hoursOfOp(libName = 'Main Library', dayOfWeek = 3, openTime = 830, closeTime = 2200)
Main4 = hoursOfOp(libName = 'Main Library', dayOfWeek = 4, openTime = 830, closeTime = 2200)
Main5 = hoursOfOp(libName = 'Main Library', dayOfWeek = 5, openTime = 830, closeTime = 1800)
Main6 = hoursOfOp(libName = 'Main Library', dayOfWeek = 6, openTime = 0, closeTime = 0)
Chem0 = hoursOfOp(libName = 'Chemistry Library', dayOfWeek = 0, openTime = 1300, closeTime = 2200)
Chem1 = hoursOfOp(libName = 'Chemistry Library', dayOfWeek = 1, openTime = 900, closeTime = 1700)
Chem2 = hoursOfOp(libName = 'Chemistry Library', dayOfWeek = 2, openTime = 900, closeTime = 1700)
Chem3 = hoursOfOp(libName = 'Chemistry Library', dayOfWeek = 3, openTime = 900, closeTime = 2200)
Chem4 = hoursOfOp(libName = 'Chemistry Library', dayOfWeek = 4, openTime = 900, closeTime = 2200)
Chem5 = hoursOfOp(libName = 'Chemistry Library', dayOfWeek = 5, openTime = 900, closeTime = 1700)
Chem6 = hoursOfOp(libName = 'Chemistry Library', dayOfWeek = 6, openTime = 1300, closeTime = 1700)
Grainger0 = hoursOfOp(libName = 'Grainger', dayOfWeek = 0, openTime = 0, closeTime = 2400)
Grainger1 = hoursOfOp(libName = 'Grainger', dayOfWeek = 1, openTime = 0, closeTime = 2400)
Grainger2 = hoursOfOp(libName = 'Grainger', dayOfWeek = 2, openTime = 0, closeTime = 2400)
Grainger3 = hoursOfOp(libName = 'Grainger', dayOfWeek = 3, openTime = 0, closeTime = 2400)
Grainger4 = hoursOfOp(libName = 'Grainger', dayOfWeek = 4, openTime = 0, closeTime = 2400)
Grainger5 = hoursOfOp(libName = 'Grainger', dayOfWeek = 5, openTime = 0, closeTime = 2400)
Grainger6 = hoursOfOp(libName = 'Grainger', dayOfWeek = 6, openTime = 0, closeTime = 2400)

ACES0.save()
ACES1.save()
ACES2.save()
ACES3.save()
ACES4.save()
ACES5.save()
ACES6.save()
UGL0.save()
UGL1.save()
UGL2.save()
UGL3.save()
UGL4.save()
UGL5.save()
UGL6.save()
Main0.save()
Main1.save()
Main2.save()
Main3.save()
Main4.save()
Main5.save()
Main6.save()
Grainger0.save()
Grainger1.save()
Grainger2.save()
Grainger3.save()
Grainger4.save()
Grainger5.save()
Grainger6.save()

hoursOfOp.objects.all()
