# Generated by Django 2.1.7 on 2019-04-05 17:37

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FloorSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libName', models.CharField(max_length=255)),
                ('floorNum', models.IntegerField(default=0)),
                ('section', models.CharField(max_length=255)),
                ('numSeats', models.IntegerField(default=0)),
                ('studyEnv', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='hoursOfOp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libName', models.CharField(max_length=255)),
                ('dayOfWeek', models.IntegerField()),
                ('openTime', models.IntegerField()),
                ('closeTime', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('libName', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('libraryDept', models.CharField(max_length=255)),
                ('numFloors', models.IntegerField(default=0)),
                ('libAddress', models.CharField(max_length=255)),
                ('reservationLink', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='recordData',
            fields=[
                ('recordID', models.UUIDField(default=uuid.UUID('36c6a8c4-5ab2-4ea9-b9ba-495b090c1564'), editable=False, primary_key=True, serialize=False)),
                ('entryTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('libName', models.CharField(max_length=255)),
                ('floorNum', models.IntegerField(default=0)),
                ('section', models.CharField(max_length=255)),
                ('dayOfWeek', models.IntegerField()),
                ('time', models.IntegerField()),
                ('count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('requestID', models.UUIDField(default=uuid.UUID('fc879ec1-d353-4b63-bf74-3fbef1fab5a7'), editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='specialDateRanges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventName', models.CharField(max_length=255)),
                ('dateTimeStart', models.DateTimeField(default=django.utils.timezone.now)),
                ('dateTimeEnd', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('username', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('passwordHash', models.CharField(max_length=255)),
                ('prefStudyEnv', models.CharField(max_length=255)),
                ('mainAddress', models.CharField(max_length=255)),
                ('favLibrary', models.CharField(max_length=255)),
                ('major', models.CharField(max_length=255)),
                ('isAdmin', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='hoursofop',
            unique_together={('libName', 'dayOfWeek')},
        ),
        migrations.AlterUniqueTogether(
            name='floorsection',
            unique_together={('libName', 'floorNum', 'section')},
        ),
    ]
