# Generated by Django 2.1.7 on 2019-03-27 18:43

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FloorSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libName', models.CharField(max_length=255)),
                ('floorNum', models.IntegerField(default=0)),
                ('section', models.CharField(max_length=255)),
                ('numSeats', models.IntegerField(default=0)),
                ('studyEnv', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='hoursOfOp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libName', models.CharField(max_length=255)),
                ('dayOfWeek', models.IntegerField()),
                ('openTime', models.IntegerField()),
                ('closeTime', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('libName', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('libraryDept', models.CharField(max_length=255)),
                ('numFloors', models.IntegerField(default=0)),
                ('libAddress', models.CharField(max_length=255)),
                ('reservationLink', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='recordData',
            fields=[
                ('date', models.DateTimeField(auto_now_add=True, primary_key=True, serialize=False)),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('requestID', models.UUIDField(default=uuid.UUID('afdcc5e6-0104-44fb-b607-e08787da5932'), editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='specialDateRanges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventName', models.CharField(max_length=255)),
                ('dateTimeStart', models.DateTimeField(default=datetime.datetime(2019, 3, 27, 13, 43, 36, 48661))),
                ('dateTimeEnd', models.DateTimeField(default=datetime.datetime(2019, 3, 27, 13, 43, 36, 49667))),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('username', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('passwordHash', models.CharField(max_length=255)),
                ('prefStudyEnv', models.CharField(max_length=255)),
                ('mainAddress', models.CharField(max_length=255)),
                ('favLibrary', models.CharField(max_length=255)),
                ('major', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='hoursofop',
            unique_together={('libName', 'dayOfWeek')},
        ),
        migrations.AlterUniqueTogether(
            name='floorsection',
            unique_together={('libName', 'floorNum', 'section')},
        ),
    ]
