# Generated by Django 2.2 on 2019-04-12 03:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recorddata',
            name='recordID',
            field=models.UUIDField(default=uuid.UUID('35518040-01d8-41a1-96de-1ce46aa39422'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='request',
            name='requestID',
            field=models.UUIDField(default=uuid.UUID('5fceaa78-70ba-4d89-a3df-a202f813e116'), editable=False, primary_key=True, serialize=False),
        ),
    ]
